spring:
  datasource:
    url: jdbc:mysql:///blog?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 5567786
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.zh: debug
  file: log/blog-dev.log
