spring:
  datasource:
    url: jdbc:mysql:///blog?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: zzz5567786
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.zh: info
  file: log/blog-pro.log
server:
  port: 8081
